# Generated by Django 5.0.1 on 2024-04-03 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policy_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('policy_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('upper_limit', models.IntegerField(blank=True, null=True)),
                ('lower_limit', models.IntegerField(blank=True, null=True)),
                ('policy_amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'policy',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('contact_message', models.CharField(max_length=5000)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useraccounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ChestDisease',
            fields=[
                ('disease_code', models.CharField(auto_created=True, max_length=30, primary_key=True, serialize=False)),
                ('specific_type', models.CharField(blank=True, max_length=250, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useraccounts.customer')),
            ],
            options={
                'db_table': 'chest_disease',
            },
        ),
        migrations.CreateModel(
            name='Dependants',
            fields=[
                ('dependants_id', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dependants_dob', models.CharField(blank=True, max_length=200, null=True)),
                ('relationship', models.CharField(blank=True, max_length=200, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccounts.customer')),
            ],
            options={
                'db_table': 'dependants',
            },
        ),
        migrations.CreateModel(
            name='GutDisease',
            fields=[
                ('disease_code', models.CharField(auto_created=True, max_length=30, primary_key=True, serialize=False)),
                ('specific_type', models.CharField(blank=True, max_length=250, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useraccounts.customer')),
            ],
            options={
                'db_table': 'gut_disease',
            },
        ),
        migrations.CreateModel(
            name='HeartDisease',
            fields=[
                ('disease_code', models.CharField(auto_created=True, max_length=30, primary_key=True, serialize=False)),
                ('specific_type', models.CharField(blank=True, max_length=250, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useraccounts.customer')),
            ],
            options={
                'db_table': 'heart_disease',
            },
        ),
        migrations.CreateModel(
            name='MentalDiseases',
            fields=[
                ('disease_code', models.CharField(auto_created=True, max_length=30, primary_key=True, serialize=False)),
                ('specific_type', models.CharField(blank=True, max_length=250, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useraccounts.customer')),
            ],
            options={
                'db_table': 'mental_diseases',
            },
        ),
        migrations.CreateModel(
            name='PolicyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useraccounts.customer')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useraccounts.policy')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationInfo',
            fields=[
                ('quotecode', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nationalid', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('phone_number', models.IntegerField(blank=True, help_text='0712345678 or +254712345678', null=True)),
                ('gender', models.CharField(max_length=10)),
                ('occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('contribution_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useraccounts.customer')),
            ],
            options={
                'db_table': 'quotationTable',
            },
        ),
    ]
