# Generated by Django 5.0.1 on 2024-04-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chestdisease',
            name='disease_code',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gutdisease',
            name='disease_code',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='heartdisease',
            name='disease_code',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mentaldiseases',
            name='disease_code',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
